name: Pull Base Images
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Pull and Save Alpine
      run: |
        docker pull --platform linux/amd64 alpine:latest
        docker save -o alpine-amd64.tar alpine:latest
    - uses: actions/upload-artifact@v4
      with:
        name: alpine-image
        path: alpine-amd64.tar

    - name: Pull and Save Ubuntu
      run: |
        docker pull --platform linux/amd64 ubuntu:latest
        docker save -o ubuntu-amd64.tar ubuntu:latest
    - uses: actions/upload-artifact@v4
      with:
        name: ubuntu-image
        path: ubuntu-amd64.tar